---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rabe-cridlib
  description: Generate RaBe CRIDs for current show, past shows, and show in the near future.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: it-reaktion
