site_name: rabe-cridlib
repo_url: https://github.com/radiorabe/python-rabe-cridlib
repo_name: radiorabe/python-rabe-cridlib

theme:
  name: "material"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - toc.integrate

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

extra:
  social:
    - icon: material/web
      link: https://rabe.ch

extra_css:
- css/style.css

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [cridlib]

nav:
  - README: index.md
  - API Reference: reference/

watch:
  - README.md
  - cridlib/
