name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@main
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', '3.9' ]
    name: Test python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install

      - run: poetry run pytest
