name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@v0.21.2
  pytest:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@v0.21.2
