name: Release

on:
  release:
    types: [created]

jobs:
  pypi:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'

      - run: poetry install

      - run: poetry build

      - name: Run twine
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.RABE_PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: true
        run: poetry run twine upload dist/*
